# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=10)),
                ('pitch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('dominanthand', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='colour',
            name='col1',
        ),
        migrations.AddField(
            model_name='colour',
            name='hexcode',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AddField(
            model_name='attempttwo',
            name='colourTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colourTwo', to='synesthesia.Colour'),
        ),
        migrations.AddField(
            model_name='attempttwo',
            name='soundTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundTwo', to='synesthesia.Sound'),
        ),
        migrations.AddField(
            model_name='attempttwo',
            name='userTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTwo', to='synesthesia.User'),
        ),
        migrations.AddField(
            model_name='attemptone',
            name='colourOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colourOne', to='synesthesia.Colour'),
        ),
        migrations.AddField(
            model_name='attemptone',
            name='soundOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundOne', to='synesthesia.Sound'),
        ),
        migrations.AddField(
            model_name='attemptone',
            name='userOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOne', to='synesthesia.User'),
        ),
    ]
