# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0003_remove_sound_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
