# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0005_auto_20171229_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
