# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0007_auto_20171229_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptone',
            name='colourOne',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='attemptone',
            name='soundOne',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
