# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0008_auto_20180105_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempttwo',
            name='colourTwo',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='attempttwo',
            name='soundTwo',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
