# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0010_auto_20180130_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
