# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synesthesia', '0011_auto_20180130_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=255),
        ),
    ]
